target 'DMPasscode', :exclusive => true do
  pod "DMPasscode", :path => "../"
end

target 'Tests', :exclusive => true do
    use_frameworks!
  pod "DMPasscode", :path => "../"
  
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
